# Source: jxboot-helmfile-resources/templates/repositories.yaml
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "dev"
  labels:
    jenkins.io/gitSync: "false"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  description: "the git repository for the Dev environment"
  provider: "https://github.com"
  providerKind: 'github'
  providerName: 'github'
  org: "phamidko"
  repo: "jx3-cluster"
  httpCloneURL: "https://github.com/phamidko/jx3-cluster.git"
  url: "https://github.com/phamidko/jx3-cluster.git"
  scheduler:
    kind: Scheduler
    name: "in-repo"
