apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-artistic-mole
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "792204942108"
    project: jenkin-307611
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: phamidko
    repository: jx3-cluster
  - key: staging
  - key: production
  ingress:
    domain: 35.225.114.101.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: phamidko
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-artistic-mole-7dd8d919752e
  - name: reports
    url: gs://reports-tf-jx-artistic-mole-7dd8d919752e
  - name: repository
    url: gs://repository-tf-jx-artistic-mole-7dd8d919752e
  vault: {}
  webhook: lighthouse
