# Source: acme/templates/cert-manager-prod-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-dev-phamid-page-p"
  labels:
    jenkins.io/letsencrypt-service: production
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  secretName: "tls-dev-phamid-page-p"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.dev.phamid.page"
  dnsNames:
    - "*.dev.phamid.page"
    - "dev.phamid.page"
